version: "3.9"

services:
  dockersample:
    image: ${DOCKER_REGISTRY-}docker-external-ffmpeg5-sample:dev
    container_name: docker-external-ffmpeg5-sample
    build:
      context: ../..
      dockerfile: demos/DockerExternalFFmpeg5Sample/Dockerfile
